dic1 = {
				"<Emoji: Face with tears of joy>" : 0,
				"<Emoji: Collision symbol>" : 100, 
				"<Emoji: Thumbs up sign>" : 200,
				"<Emoji: Kissing face>" : 1,
				"<Emoji: Face with look of triumph>" : 2,
				"<Emoji: Drooling face>" : 3,
				"<Emoji: Face with open mouth and cold sweat>" : 4,
				"<Emoji: Lying face>" : 5,
				"<Emoji: Worried face>" : 6,
				"<Emoji: Smiling face with open mouth>" : 7,
				"<Emoji: Sign of the horns>" : 8,
				"<Emoji: Star-struck>" : 9,
				"<Emoji: Heavy red heart>" : 10,
				"<Emoji: Flushed face>" : 11,
				"<Emoji: Skull and crossbones>" : 12,
				"<Emoji: Nauseated face>" : 13,
				"<Emoji: Face with cold sweat>" : 14,
				"<Emoji: Face throwing a kiss>" : 15,
				"<Emoji: See-no-evil monkey>" : 16,
				"<Emoji: Astonished face>" : 17,
				"<Emoji: Fisted hand sign>" : 18,
				"<Emoji: Money-mouth face>" : 19,
				"<Emoji: Neutral face>" : 20,
				"<Emoji: Party popper>" : 21,
				"<Emoji: Face with monocle>" : 22,
				"<Emoji: Face with cowboy hat>" : 23,
				"<Emoji: Confounded face>" : 24,
				"<Emoji: Fearful face>" : 25,
				"<Emoji: Disappointed but relieved face>" : 26,
				"<Emoji: Extraterrestrial alien>" : 27,
				"<Emoji: Crying face>" : 28,
				"<Emoji: Sleepy face>" : 29,
				"<Emoji: Exploding head>" : 30,
				"<Emoji: Frowning face>" : 31,
				"<Emoji: Face with thermometer>" : 32,
				"<Emoji: Kissing face with closed eyes>" : 33,
				"<Emoji: Face vomiting>" : 34,
				"<Emoji: Hugging face>" : 35,
				"<Emoji: Frowning face with open mouth>" : 36,
				"<Emoji: Face with rolling eyes>" : 37,
				"<Emoji: Face with hand over mouth>" : 38,
				"<Emoji: Persevering face>" : 39,
				"<Emoji: Face with raised eyebrow>" : 40,
				"<Emoji: Smirking face>" : 41,
				"<Emoji: Angry face>" : 42,
				"<Emoji: Ok hand sign>" : 43,
				"<Emoji: Kissing face with smiling eyes>" : 44,
				"<Emoji: Upside-down face>" : 45,
				"<Emoji: Rolling on the floor laughing>" : 46,
				"<Emoji: Slightly frowning face>" : 47,
				"<Emoji: Relieved face>" : 48,
				"<Emoji: Nerd face>" : 49,
				"<Emoji: Dizzy face>" : 50,
				"<Emoji: Face with head-bandage>" : 51,
				"<Emoji: Face with medical mask>" : 52,
				"<Emoji: Tired face>" : 53,
				"<Emoji: Imp>" : 54,
				"<Emoji: Smiling face with open mouth and cold sweat>" : 55,
				"<Emoji: Smiling face>" : 56,
				"<Emoji: Face with stuck-out tongue and tightly-closed eyes>" : 57,
				"<Emoji: Grinning face with smiling eyes>" : 58,
				"<Emoji: Face screaming in fear>" : 59,
				"<Emoji: Grinning face>" : 60,
				"<Emoji: Smiling face with sunglasses>" : 61,
				"<Emoji: Zipper-mouth face>" : 62,
				"<Emoji: Face with open mouth>" : 63,
				"<Emoji: Sneezing face>" : 64,
				"<Emoji: Pile of poo>" : 65,
				"<Emoji: Grimacing face>" : 66,
				"<Emoji: Loudly crying face>" : 67,
				"<Emoji: Face with stuck-out tongue and winking eye>" : 68,
				"<Emoji: Clown face>" : 69,
				"<Emoji: Face savouring delicious food>" : 70,
				"<Emoji: Smiling face with horns>" : 71,
				"<Emoji: Smiling face with halo>" : 72,
				"<Emoji: Expressionless face>" : 73,
				"<Emoji: Skull>" : 74,
				"<Emoji: Anguished face>" : 75,
				"<Emoji: Smiling face with heart-shaped eyes>" : 76,
				"<Emoji: Shushing face>" : 77,
				"<Emoji: Winking face>" : 78,
				"<Emoji: Love letter>" : 79,
				"<Emoji: Face with stuck-out tongue>" : 80,
				"<Emoji: Disappointed face>" : 81,
				"<Emoji: Thinking face>" : 82,
				"<Emoji: Confused face>" : 83,
				"<Emoji: Slightly smiling face>" : 84,
				"<Emoji: Face with symbols over mouth>" : 85,
				"<Emoji: Smiling face with open mouth and smiling eyes>" :  86,
				"<Emoji: Pouting face>" : 87,
				"<Emoji: Weary face>" : 88,
				"<Emoji: Crazy face>" : 89,
				"<Emoji: Unamused face>" : 90,
				"<Emoji: Sleeping face>" : 91,
				"<Emoji: Victory hand>" : 92,
				"<Emoji: Hushed face>" : 93,
				"<Emoji: Smiling face with smiling eyes>" : 94,
				"<Emoji: Pensive face>" : 95,
				"<Emoji: Confetti ball>" : 96,
				"<Emoji: Fire>" : 97,
				"<Emoji: Smiling face with open mouth and tightly-closed eyes>" : 98,
				"<Emoji: Face without mouth>" : 99	
}


dic2 = {
				"<Emoji: Face with tears of joy>" : 0,
				"<Emoji: Collision symbol>" : 100, 
				"<Emoji: Thumbs up sign>" : 200,
				"<Emoji: Thinking face>" : 1,
				"<Emoji: Smiling face with smiling eyes>" : 2,
				"<Emoji: Zipper-mouth face>" : 3,
				"<Emoji: Face vomiting>" : 4,
				"<Emoji: Upside-down face>" : 5,
				"<Emoji: Face with look of triumph>" : 6,
				"<Emoji: Grimacing face>" : 7,
				"<Emoji: Confused face>" : 8,
				"<Emoji: Weary face>" : 9,
				"<Emoji: Lying face>" : 10,
				"<Emoji: Crying face>" : 11,
				"<Emoji: Face with medical mask>" : 12,
				"<Emoji: Expressionless face>" : 13,
				"<Emoji: Love letter>" : 14,
				"<Emoji: Disappointed face>" : 15,
				"<Emoji: Face with stuck-out tongue and winking eye>" : 16,
				"<Emoji: Heavy red heart>" : 17,
				"<Emoji: Anguished face>" : 18,
				"<Emoji: Nerd face>" : 19,
				"<Emoji: Grinning face with smiling eyes>" : 20,
				"<Emoji: Face with stuck-out tongue and tightly-closed eyes>" : 21,
				"<Emoji: Smiling face>" : 22,
				"<Emoji: Disappointed but relieved face>" : 23,
				"<Emoji: Skull>" : 24,
				"<Emoji: Clown face>" : 25,
				"<Emoji: Smiling face with heart-shaped eyes>" : 26,
				"<Emoji: Kissing face with closed eyes>" : 27,
				"<Emoji: Smiling face with open mouth>" : 28,
				"<Emoji: Pouting face>" : 29,
				"<Emoji: Face with rolling eyes>" : 30,
				"<Emoji: Shushing face>" : 31,
				"<Emoji: Kissing face with smiling eyes>" : 32,
				"<Emoji: Money-mouth face>" : 33,
				"<Emoji: Nauseated face>" : 34,
				"<Emoji: Smiling face with sunglasses>" : 35,
				"<Emoji: Neutral face>" : 36,
				"<Emoji: Tired face>" : 37,
				"<Emoji: Grinning face>" : 38,
				"<Emoji: Confounded face>" : 39,
				"<Emoji: Face with open mouth and cold sweat>" : 40,
				"<Emoji: Face with raised eyebrow>" : 41,
				"<Emoji: Pensive face>" : 42,
				"<Emoji: Astonished face>" : 43,
				"<Emoji: Fearful face>" : 44,
				"<Emoji: Face with cowboy hat>" : 45,
				"<Emoji: Extraterrestrial alien>" : 46,
				"<Emoji: Smiling face with horns>" : 47,
				"<Emoji: Persevering face>" : 48,
				"<Emoji: Smiling face with open mouth and tightly-closed eyes>" : 49,
				"<Emoji: Face with monocle>" : 50,
				"<Emoji: Ok hand sign>" : 51,
				"<Emoji: Face with open mouth>" : 52,
				"<Emoji: Face screaming in fear>" : 53,
				"<Emoji: Kissing face>" : 54,
				"<Emoji: Winking face>" : 55,
				"<Emoji: Fisted hand sign>" : 56,
				"<Emoji: Crazy face>" : 57,
				"<Emoji: Worried face>" : 58,
				"<Emoji: Slightly smiling face>" : 59,
				"<Emoji: Smiling face with halo>" : 60,
				"<Emoji: Sleeping face>" : 61,
				"<Emoji: Face with cold sweat>" : 62,
				"<Emoji: Confetti ball>" : 63,
				"<Emoji: Unamused face>" : 64,
				"<Emoji: Slightly frowning face>" : 65,
				"<Emoji: Skull and crossbones>" : 66,
				"<Emoji: Fire>" : 67,
				"<Emoji: Sneezing face>" : 68,
				"<Emoji: Face with hand over mouth>" : 69,
				"<Emoji: Face throwing a kiss>" : 70,
				"<Emoji: Face with stuck-out tongue>" : 71,
				"<Emoji: Imp>" : 72,
				"<Emoji: Exploding head>" : 73,
				"<Emoji: Hushed face>" : 74,
				"<Emoji: Smiling face with open mouth and smiling eyes>" :  75,
				"<Emoji: Dizzy face>" : 76,
				"<Emoji: Victory hand>" : 77,
				"<Emoji: Star-struck>" : 78,
				"<Emoji: Smirking face>" : 79,
				"<Emoji: Smiling face with open mouth and cold sweat>" : 80,
				"<Emoji: Party popper>" : 81,
				"<Emoji: Relieved face>" : 82,
				"<Emoji: Face savouring delicious food>" : 83,
				"<Emoji: Face with thermometer>" : 84,
				"<Emoji: See-no-evil monkey>" : 85,
				"<Emoji: Rolling on the floor laughing>" : 86,
				"<Emoji: Frowning face>" : 87,
				"<Emoji: Hugging face>" : 88,
				"<Emoji: Face with symbols over mouth>" : 89,
				"<Emoji: Sleepy face>" : 90,
				"<Emoji: Face with head-bandage>" : 91,
				"<Emoji: Pile of poo>" : 92,
				"<Emoji: Drooling face>" : 93,
				"<Emoji: Frowning face with open mouth>" : 94,
				"<Emoji: Flushed face>" : 95,
				"<Emoji: Loudly crying face>" : 96,
				"<Emoji: Sign of the horns>" : 97,
				"<Emoji: Angry face>" : 98,
				"<Emoji: Face without mouth>" : 99				
}

dic3 = {
				"<Emoji: Face with tears of joy>" : 0,
				"<Emoji: Collision symbol>" : 100, 
				"<Emoji: Thumbs up sign>" : 200,
				"<Emoji: Face with stuck-out tongue and tightly-closed eyes>" : 1,
				"<Emoji: Face with cowboy hat>" : 2,
				"<Emoji: Pouting face>" : 3,
				"<Emoji: Sign of the horns>" : 4,
				"<Emoji: Face savouring delicious food>" : 5,
				"<Emoji: Kissing face>" : 6,
				"<Emoji: Sleeping face>" : 7,
				"<Emoji: Disappointed but relieved face>" : 8,
				"<Emoji: Fearful face>" : 9,
				"<Emoji: Winking face>" : 10,
				"<Emoji: Clown face>" : 11,
				"<Emoji: Heavy red heart>" : 12,
				"<Emoji: Grimacing face>" : 13,
				"<Emoji: Face with cold sweat>" : 14,
				"<Emoji: Smirking face>" : 15,
				"<Emoji: Face with head-bandage>" : 16,
				"<Emoji: Confounded face>" : 17,
				"<Emoji: Pile of poo>" : 18,
				"<Emoji: Face without mouth>" : 19,
				"<Emoji: Hushed face>" : 20,
				"<Emoji: Smiling face with sunglasses>" : 21,
				"<Emoji: Grinning face>" : 22,
				"<Emoji: Star-struck>" : 23,
				"<Emoji: Unamused face>" : 24,
				"<Emoji: Face screaming in fear>" : 25,
				"<Emoji: Face with open mouth>" : 26,
				"<Emoji: Ok hand sign>" : 27,
				"<Emoji: Victory hand>" : 28,
				"<Emoji: Face with monocle>" : 29,
				"<Emoji: Loudly crying face>" : 30,
				"<Emoji: Face with raised eyebrow>" : 31,
				"<Emoji: Thinking face>" : 32,
				"<Emoji: Shushing face>" : 33,
				"<Emoji: Frowning face>" : 34,
				"<Emoji: Sneezing face>" : 35,
				"<Emoji: Love letter>" : 36,
				"<Emoji: Face with thermometer>" : 37,
				"<Emoji: Weary face>" : 38,
				"<Emoji: Extraterrestrial alien>" : 39,
				"<Emoji: Fisted hand sign>" : 40,
				"<Emoji: Face with rolling eyes>" : 41,
				"<Emoji: Face with open mouth and cold sweat>" : 42,
				"<Emoji: Nerd face>" : 43,
				"<Emoji: Dizzy face>" : 44,
				"<Emoji: Skull>" : 45,
				"<Emoji: Face with medical mask>" : 46,
				"<Emoji: Smiling face with horns>" : 47,
				"<Emoji: Smiling face with halo>" : 48,
				"<Emoji: Kissing face with closed eyes>" : 49,
				"<Emoji: Smiling face with open mouth and tightly-closed eyes>" : 50,
				"<Emoji: Smiling face with open mouth and smiling eyes>" :  51,
				"<Emoji: Face with hand over mouth>" : 52,
				"<Emoji: Face with symbols over mouth>" : 53,
				"<Emoji: Angry face>" : 54,
				"<Emoji: Slightly frowning face>" : 55,
				"<Emoji: Worried face>" : 56,
				"<Emoji: Money-mouth face>" : 57,
				"<Emoji: See-no-evil monkey>" : 58,
				"<Emoji: Zipper-mouth face>" : 59,
				"<Emoji: Face vomiting>" : 60,
				"<Emoji: Astonished face>" : 61,
				"<Emoji: Party popper>" : 62,
				"<Emoji: Rolling on the floor laughing>" : 63,
				"<Emoji: Flushed face>" : 64,
				"<Emoji: Face with stuck-out tongue>" : 65,
				"<Emoji: Imp>" : 66,
				"<Emoji: Hugging face>" : 67,
				"<Emoji: Smiling face with heart-shaped eyes>" : 68,
				"<Emoji: Anguished face>" : 69,
				"<Emoji: Smiling face>" : 70,
				"<Emoji: Confused face>" : 71,
				"<Emoji: Pensive face>" : 72,
				"<Emoji: Smiling face with open mouth and cold sweat>" : 73,
				"<Emoji: Exploding head>" : 74,
				"<Emoji: Face throwing a kiss>" : 75,
				"<Emoji: Lying face>" : 76,
				"<Emoji: Face with look of triumph>" : 77,
				"<Emoji: Persevering face>" : 78,
				"<Emoji: Skull and crossbones>" : 79,
				"<Emoji: Slightly smiling face>" : 80,
				"<Emoji: Tired face>" : 81,
				"<Emoji: Smiling face with open mouth>" : 82,
				"<Emoji: Neutral face>" : 83,
				"<Emoji: Expressionless face>" : 84,
				"<Emoji: Face with stuck-out tongue and winking eye>" : 85,
				"<Emoji: Disappointed face>" : 86,
				"<Emoji: Upside-down face>" : 87,
				"<Emoji: Smiling face with smiling eyes>" : 88,
				"<Emoji: Kissing face with smiling eyes>" : 89,
				"<Emoji: Nauseated face>" : 90,
				"<Emoji: Frowning face with open mouth>" : 91,
				"<Emoji: Relieved face>" : 92,
				"<Emoji: Crazy face>" : 93,
				"<Emoji: Sleepy face>" : 94,
				"<Emoji: Confetti ball>" : 95,
				"<Emoji: Grinning face with smiling eyes>" : 96,
				"<Emoji: Crying face>" : 97,
				"<Emoji: Fire>" : 98,
				"<Emoji: Drooling face>" : 99
}